# Generated by Django 4.1.1 on 2022-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
